### ISSUE TITLE
Reconstuction from a set of macro-images without exif data

### ISSUE THREAD

**Issue by SOSTaler** [simonfuhrmann/mve#472] opened 2019-04-01 15:50 UTC
(This is strictly speaking not an issue with MVE)
Thanks for publicizing your project. I have used it successfully with a wide variety of image-sets taken with standard digital cameras. I am now trying to use images taken with a weak optical microscope (x50 - x150) to construct surface features around 0.10 mm in size.

When I use images acquired with the microscope, the MVE reconstruction pipeline gives errors quite early on, complaining about non-existing EXIF info. (Apparently the cam built into the microscope does not integrate EXIF data into the output images)
So I am wondering if I could do the reconstruction by manually specifying some required(?) exif information, but I have no idea about what that should look like to make MVE happy.

But maybe it is not the missing exif info and there is something else to consider when working with this kind of "macro' images that I have not thought of?

I am very keen to know if you have an idea on what I could do to bring my project forward.
Cheers

**Comment by simonfuhrmann** [comment] 2019-04-01 18:41
What is the focal length of the microscope (35mm sensor equivalent)?
You could inject EXIF data into your JPEG images, in particular the "35mm equivalent" tag (0xa405, FocalLengthIn35mmFormat, int16u) using a tool like `exiftool`. If you do that, the warning should go away. Let me know if it works.

**Comment by fluffrabbit** [comment] 2019-04-06 00:11
Absolute novice photogrammator here. I used 123D Catch when it first came out, which used a smartphone's internal camera for MVS reconstruction, presumably without accurate initial intrinsics considering how unreliable low-end smartphone cameras can be. It sort of worked.

MVE is my new favorite tool, though I have not had much success with it so far. I am playing around with the EXIF now. In situations like smartphones, Internet images, and movie frames, the focal length will usually not be known, and that just sucks. There is of course active research being done in this area, such as [this paper](https://arxiv.org/abs/1810.00128).

I frankly don't know how photogrammetry can exist as a thing if I feed it 40 angles of a boot and it can't reconstruct without knowing the focal length in advance, but I see people doing reconstruction with great success so it's probably just me.

**Comment by simonfuhrmann** [comment] 2019-04-06 05:07
Recovering the focal length from images is mathematically somewhat ambiguous and often leads to inaccurate focal length estimates. Starting the bundle adjustment with an inaccurate focal length, SfM is likely to fail or produce really bad results. So it's important to have somewhat reasonable starting values for focal length.

Fortunately most cameras put the focal length in the EXIF tags. The problem is, however, that this focal length is relative to the sensor size of the device, which is not indicated in the EXIF tags. MVE has a database of cameras and sensor sizes to compute the effective focal length. It's horribly outdated and incomplete, but if you have a camera that is currently missing from the database, it's pretty easy to add.

The FocalLengthIn35mmFormat EXIF tag solves this issue, but most cameras don't write it. :(

**Comment by fluffrabbit** [comment] 2019-04-06 05:31
And trying to write that tag with exiftool doesn't result in it being displayed in the image properties in the Thunar file manager, unless I'm using exiftool wrong.

I know my camera is micro 4/3, so 1/2 crop factor, and I know my 18-55mm lens was all the way wide, so my 35mm equivalent focal length is 36, but as for how that translates to "normalized focal length", what I should do about the other intrinsics, or how my camera setting the "focal length" property to 0.0 affects things, I don't know. EXIF is a truly awful system in practice.

**Comment by simonfuhrmann** [comment] 2019-04-17 18:49
I'm not sure if Thunar displays the 35mm equivalent tag. Just use exiftool to print out the EXIF information and check if it's there. For your micro 4/3 camera, just multiply the focal length with 2 and write it to the 35mm equivalent tag.

**Comment by fluffrabbit** [comment] 2019-04-17 21:25
You're right, my file manager wasn't showing the 35mm focal length, and the tool did set the tag. `exiftool` does dump the EXIF info when you run it on the image without parameters, but it's not a user-friendly program and the manpage reads in a legalistic and boring way with no n00b guide, so here's the short version:

For a 69 mm equivalent lens, do: `exiftool -FocalLengthIn35mmFormat=69 -overwrite_original IMAGE.JPG`

To see that it worked, do: `exiftool IMAGE.JPG | grep 35mm`

Here is the shell script I used to fix that parameter on my images; now hopefully that's all the data MVE needs:

    #!/bin/sh
    for f in *.JPG
    do
        exiftool -FocalLengthIn35mmFormat=36 -overwrite_original "$f"
    done

**Comment by simonfuhrmann** [comment] 2019-04-18 19:27
When you run MVE on images where it can't find the focal length it should complain with something like `"Warning: Using fallback focal length for view xxx"`. Once the EXIF information is recognized, this complaint should go away.

Note that after injecting EXIF into your input JPEG images, you have to run makescene again, as it extracts and stores the EXIF blob separately in the views.

**Comment by fluffrabbit** [comment] 2019-04-19 18:09
The 35mm format tag seems to get the reconstruction as good as it's going to get. Noisy and with gaps where the shadows were, but it's a start.

Regarding OP, I would think the lens system of the microscope combined with the digital zoom would result in essentially parallel orthographic projection, no? I don't know if these same algorithms would work in that case.

**Comment by simonfuhrmann** [comment] 2019-04-19 18:32
Yes, I have the same concern. I might work if there is enough rotation, but if it's just a shifted version of the scene with essentially an orthographic projection, that's not going to work.

I'm closing this issue. Feel free to re-open if necessary.

**Closed by simonfuhrmann** 2019-04-19 18:32 UTC
