### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by hellocatfood** [simonfuhrmann/mve#149] opened 2015-05-25 11:40 UTC
I'm using a precompiled version of umve from GetDeb on Ubuntu 15.04 on a Dell XPS13 http://www.getdeb.net/software/mve

When I click on the Scene inspect or SfM Reconstruct tab the program crashes and I get the following error:

```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::runtime_error'
  what():  GL error: 1281
Aborted (core dumped)
```

**Comment by simonfuhrmann** [comment] 2015-05-25 12:09
I am guessing the problem is that the pre-compiled version of OpenGL and the one on your system are incompatible. Try compiling the software on your own. You need OpenGL 3.3 or later for UMVE.

**Comment by ckorn** [comment] 2015-05-25 13:37
Hi @simonfuhrmann ,

the package on GetDeb has been created by me. Is this a packaging bug? The package is built in a chroot environment. I don't know what OpenGL version is available there but I did not see that crash before.
This is the build log if it is of any use:
http://zulu309.server4you.de/build/logs/mve_0.0.0+git20150523-1~getdeb1-i386-20150523-2200

**Comment by simonfuhrmann** [comment] 2015-05-25 14:52
I don't know. If the software works once hellocatfood compiles it locally, it seems like a packaging bug. I'm not an expert, but the OpenGL header is usually not provided by a package but the graphics chipset vendor. Can this cause issues?

**Comment by simonfuhrmann** [comment] 2015-05-30 12:40
If there is no more feedback, I will close this. OpenGL errors are usually not related to MVE, but rather to the system configuration.

**Closed by simonfuhrmann** 2015-05-30 12:40 UTC

**Comment by hellocatfood** [comment] 2015-06-03 16:41
I have just tried compiling and running umve on my system and I receive no errors when running `./umve` (or no terminal output at all).

I'm using OpenGL version 3.0 Mesa 10.5.2
