### ISSUE TITLE
sfmrecon constructs correct sparse point cloud, but highly suspicious camera trajectory

### ISSUE THREAD

**Issue by mikeroberts3000** [simonfuhrmann/mve#267] opened 2016-10-20 01:31 UTC
Hello there,

Please allow me to introduce myself. My name is Mike Roberts. I'm a PhD student in the computer graphics lab at Stanford. Let me start by saying thanks so much for all the hard work you put into MVE. I've been experimenting with MVE on a photorealistic synthetic scene, and I noticed some suspicious issues during the SFM step of the pipeline.

First, I'll describe the synthetic images I'm using for my experiments. I'm using a video game engine to render images from above a synthetic scene looking down (with the camera's up vector pointing North). Here is what my scene looks like from very high above.

![overview](https://cloud.githubusercontent.com/assets/2341965/19540886/5b7a308c-9617-11e6-9943-0e9ae8d13e08.jpg)

Roughly speaking, the camera trajectory in my experiments forms a 10x10 planar rectangle pattern above the scene, where the images are ordered in scanline order, like this.

![overview](https://cloud.githubusercontent.com/assets/2341965/19541052/60633390-9618-11e6-9eac-d517354b3d09.jpg)

Note that in the above image, I'm only showing 5 scanlines for the purposes of illustration. In my experiments, I actually render 10 scanlines, each with 10 images, numbered like this.

```
00 01 02 ... 09
10 11 12 ... 19
...
90 91 92 ... 99
```

Now, let's have a look at a few of the images.

00
![0000](https://cloud.githubusercontent.com/assets/2341965/19540496/c6f0aed4-9614-11e6-8f4b-4f5ac6d87188.jpg)

05
![0005](https://cloud.githubusercontent.com/assets/2341965/19540677/ff00cb8c-9615-11e6-825e-e7540849b534.jpg)

09
![0009](https://cloud.githubusercontent.com/assets/2341965/19540647/c76e037e-9615-11e6-8d3b-d5d26a540bdf.jpg)

50
![0050](https://cloud.githubusercontent.com/assets/2341965/19540689/0e464072-9616-11e6-941a-f10c9215b290.jpg)

55
![0055](https://cloud.githubusercontent.com/assets/2341965/19540691/14887f36-9616-11e6-85a3-f93a2e73145e.jpg)

59
![0059](https://cloud.githubusercontent.com/assets/2341965/19540695/1982430a-9616-11e6-9b94-7033927432ba.jpg)

90
![0090](https://cloud.githubusercontent.com/assets/2341965/19540651/d0f52b2a-9615-11e6-9c6b-bbc9f8de95fd.jpg)

95
![0095](https://cloud.githubusercontent.com/assets/2341965/19540705/2241d4c4-9616-11e6-8155-944f9c5739e7.jpg)

99
![0099](https://cloud.githubusercontent.com/assets/2341965/19540656/d661f78c-9615-11e6-91e9-3d1b9cb92d76.jpg)

From these images, we see that my camera trajectory starts at the northwest corner of the scene, and ends in the southeast corner of the scene. Moreover, my camera trajectory clearly sees both vertical side faces of the central walkway. In other words, the rectangle spanned by my camera trajectory is roughly symmetrical about the central walkway.

Ok, now for the suspicious behavior. First, I run `makescene` to make an MVE scene as follows.

```
makescene -i IMAGE_DIR SCENE_DIR
```

Next, I run `sfmrecon` to run the SFM step of the pipeline as follows.

```
sfmrecon SCENE_DIR
```

Running sfmrecon yields a reasonable pointcloud. Here, I generate a PLY file using `bundle2pset` and visualize it in MeshLab. I have oriented the following visualization so that we're looking down at the pointcloud from above, where North is up. Notice that the circular area at the end of the walkway is correctly reconstructed, as are the pillars on the sides of the walkway.

![image](https://cloud.githubusercontent.com/assets/2341965/19541430/21ccb1e4-961b-11e6-8195-e0c9a9df35d7.png)

However, when I manually extract the camera positions and keypoint positions from `synth_0.out`, I start to see some suspicious behavior.

Here, I render the (estimated) camera positions and the keypoint positions together using Mayavi. The camera positions are colored by the order they appear in `synth_0.out` using the standard jet colormap. Blue is the beginning of the sequence, red is the end of the sequence. The keypoint positions are all colored white. I have oriented the following visualization so that we're looking down at the cameras and keypoints from above, where North is up.

![image](https://cloud.githubusercontent.com/assets/2341965/19541651/c132c506-961c-11e6-8e30-cf9db01156aa.png)

Here is an oblique view of the same scene.

![image](https://cloud.githubusercontent.com/assets/2341965/19541662/d8b3f434-961c-11e6-9287-be8745f4baff.png)

There are two suspicious errors in these images. First, the overall rectangle shape of estimated camera trajectory seems to be exactly correct except for a translation. It is perhaps even more suspicious, that the translation required to fix the problem seems to be roughly half the width and height of the rectangle spanned by the estimated camera trajectory. Second, the order of the cameras in `synth_0.out` is **exactly** backwards (i.e., exactly the opposite order of the images on disk, using the scanline indexing strategy described above).

It is worth mentioning that the images are in the correct order when I look into the `views/view_XXXX.mve` folders.

It is also worth mentioning that when I run these same images through VisualSFM (which is admittedly using a different SFM algorithm under the hood), I get the correct camera positions. Here is the VisualSFM output. Again, I am viewing the scene from above the scene looking down, and North is up.

![image](https://cloud.githubusercontent.com/assets/2341965/19542726/8f97edce-9625-11e6-81e4-3c64e0466202.png)

Notice that the camera positions are symmetrical about the central walkway in the scene. Here is the same scene viewed from a different angle.

![image](https://cloud.githubusercontent.com/assets/2341965/19542753/e70835d2-9625-11e6-9d9b-61e9fc0ebe0f.png)

And finally, here is one more interesting observation. If I run `makescene` and pass the NVM file from VisualSFM as input, and then manually extract the camera positions and keypoint positions from the resulting `synth_0.out` file as I did previously, I observe correct keypoint positions, but corrupted camera positions.

![image](https://cloud.githubusercontent.com/assets/2341965/19542780/2349f256-9626-11e6-8a31-b4d72ebbb24a.png)

Notice that the camera positions are erroneously rotated so they are no longer on a flat plane above the scene.

I've uploaded all my test images here, in case this is helpful. I can also post my (small, self-contained) Python snippets for how I'm generating these plots and extracting positions from `synth_0.out`, etc.

https://www.dropbox.com/s/ji6y5d5hpbhi8zg/mike_roberts_mve_issue_report_images.zip?dl=0

**Comment by nmoehrle** [comment] 2016-10-20 08:54
I haven't had a chance to look at the data yet but to me this looks like a mix up between camera position and camera translation. The two are related by `t = -R * c` ([see Math-Cookbook](https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook)). Could you post the python script or show a rendering of the scene in UMVE? That would show if the issue is in the extraction of camera positions.

**Comment by nmoehrle** [comment] 2016-10-20 14:35
I've reconstructed the scene with MVE and everything looks fine so I still believe that the you extract the translations from the bundle file and interpret them as positions.

The view with id zero (corresponding to image 0000.jpg) is in the top left corner:
![screeny](https://cloud.githubusercontent.com/assets/4200007/19564095/10ba24ba-96eb-11e6-906e-6966543d1c1c.png)

Rendering one of the central views (id 54) shows an accurate alignment:
![original](https://cloud.githubusercontent.com/assets/4200007/19564102/15d43d6e-96eb-11e6-97d9-aced7fda3f88.png)
![rephoto](https://cloud.githubusercontent.com/assets/4200007/19564108/1b8fb8c8-96eb-11e6-8243-cd8891823782.png)

**Comment by mikeroberts3000** [comment] 2016-10-20 20:37
@nmoehrle Ah, thanks so much for the note. I totally forgot about the UMVE viewer! Perfect place to start. Indeed, the camera trajectory looks correct in UMVE.

![image](https://cloud.githubusercontent.com/assets/2341965/19553825/beb99eb4-966a-11e6-8b3d-89160b22ea87.png)

Your intuition is spot on. To display the camera positions, I was just taking the raw "translation" values described in the bundler documentation (see image below) out of `synth_0.out` and displaying those as points in world space.

![image](https://cloud.githubusercontent.com/assets/2341965/19554192/57ed7bae-966c-11e6-8348-a8fb4d65ee27.png)

But what I really need to do is compute the camera centers according to `t = -R * c` as you suggest, and display those instead. Thanks again for looking into this.

Cheers,
Mike

**Comment by simonfuhrmann** [comment] 2016-10-21 13:19
Hi Mike,

glad you solved it. Note also that you should not rely on the synth_0.out file for any data except the point cloud. The actual camera positions are in the views, `views/view_0000.mve/meta.ini`. They are probably the same, but `meta.ini` is what MVE actually works with.

Closing this. Feel free to reopen if you have more questions.
Simon

**Closed by simonfuhrmann** 2016-10-21 13:19 UTC
