### ISSUE TITLE
How to convert ByteImage::ConstPtr image MVE into Opencv cv::Mat

### ISSUE THREAD

**Issue by xialang2012** [simonfuhrmann/mve#254] opened 2016-09-01 01:49 UTC
I created a image 

`ByteImage::Ptr textureImg = ByteImage::create(width, height, 1);`

in mve. After some process steps were done by using mve library, I converted it in to Opencv. So I used

`cv::Mat texture(textureImg->width(), textureImg->height(), CV_8UC1, const_cast<uint8_t*>(textureImg->get_data_pointer()));`

but the result seems not correctly. How does the mve arrange the images pixels in the std::Vector<T>, Could you give me some help. Thank you.

**Comment by xialang2012** [comment] 2016-09-01 06:23
An other problem about the makescene application is that it is not support to process the 16bits tiff file.
For example, converting the 16bit tif files to mve format files by using the command

`makescene.exe -i D:\recon0\16bit 16bit-res`

but the 
https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_io.cc#L56
returns a ByteImage::Ptr, and the makescene app crashed.

**Comment by simonfuhrmann** [comment] 2016-09-01 12:01
The pixels in the image are arranged in row-major format, and all color channels of a pixel follow in order. I don't know how OpenCV expects the data. Have you tried transposing the image/matrix? 

Impoting 16 bit images should be possible but I would have to look into it.

**Comment by xialang2012** [comment] 2016-09-02 05:26
No, I have not tried transposing the image. For the single channel image, both the OpenCV Mat and MVE own the same pixels arrangement method, but there are some differences for the 3 channels image. 

I have temporary changed
https://github.com/simonfuhrmann/mve/blob/master/apps/makescene/makescene.cc#L183
```
mve::ImageBase::Ptr
load_any_image (std::string const& fname, std::string* exif)
{
	mve::ByteImage::Ptr img_8 = load_8bit_image(fname, exif);
        if (img_8 != nullptr)
            return img_8;

	mve::RawImage::Ptr img_16 = load_16bit_image(fname);
	if (img_16 != nullptr)
		return img_16;
        ....
```
to

```
mve::ImageBase::Ptr
load_any_image (std::string const& fname, std::string* exif)
{
	mve::RawImage::Ptr img_16 = load_16bit_image(fname);
	if (img_16 != nullptr)
		return img_16;
	
	mve::ByteImage::Ptr img_8 = load_8bit_image(fname, exif);
    if (img_8 != nullptr)
        return img_8;
    .....
```

to make it works on Windows.

**Comment by xialang2012** [comment] 2016-09-02 05:41
An other question is I need to do gamma correction for 16 bit images, and I found the gamma correction at https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_tools.cc#L171 for 8 bits images

```
void
gamma_correct (ByteImage::Ptr image, float power)
{
    if (image == nullptr)
        throw std::invalid_argument("Null image given");

    uint8_t lookup[256];
    for (int i = 0; i < 256; ++i)
        lookup[i] = static_cast<uint8_t>(std::pow(i / 255.0f, power)
            * 255.0f + 0.5f);
    for (int i = 0; i < image->get_value_amount(); ++i)
        image->at(i) = lookup[image->at(i)];
}
```

I wonder if I can only change the 256 to 65536 in this function to make it work, as belows
```
void
gamma_correct (ByteImage::Ptr image, float power)
{
    if (image == nullptr)
        throw std::invalid_argument("Null image given");

    uint8_t lookup[65536];
    for (int i = 0; i < 65536; ++i)
        lookup[i] = static_cast<uint8_t>(std::pow(i / 65536.0f, power)
            * 65535.0f + 0.5f);
    for (int i = 0; i < image->get_value_amount(); ++i)
        image->at(i) = lookup[image->at(i)];
}
```

**Comment by simonfuhrmann** [comment] 2016-09-02 08:34
In theory, yes. Except that you also need to fix the type of the lookup table. With Raw images, however, it's usually trickier, because the white point may not be at 2^16. This depends on the camera sensor (usually they have 12 bits) and on the software that produced the image.

For example, if your image actually only uses 12 bits, this gamma correction will not work as expected.

**Comment by xialang2012** [comment] 2016-09-02 08:44
Thank you, it is very difficult for me to make decision. Since the sensor records the image in 12 bits, but the value of the first channel is the sum of the other channels, the max value of this channel will great than 2^12... May be I should create

`gamma_correct_16bit(RawImage::Ptr image, float power)`

and 

`gamma_correct_12bit(RawImage::Ptr image, float power)`

to solve it.

**Comment by simonfuhrmann** [comment] 2016-09-02 09:44
It might be a good idea to use a third party software to do proper raw conversion for you, if possible. Lightroom, dcraw, etc.

**Comment by simonfuhrmann** [comment] 2016-09-06 18:41
Closing this. Feel free to re-open if you think the issue is related to MVE.

**Closed by simonfuhrmann** 2016-09-06 18:41 UTC
